sonar.projectKey=nx-1
sonar.projectName=nx-1
sonar.projectVersion=1.0.0

sonar.host.url=http://localhost:9000

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.language=py
sonar.python.version=3.11

sonar.exclusions=**/test_*.py,**/*_test.py,.pytest_cache/**,htmlcov/**,*.pyc,__pycache__/**

sonar.coverage.exclusions=tests/**,test_*.py,**/*_test.py,.pytest_cache/**,htmlcov/**
sonar.python.coverage.reportPaths=coverage.xml
